### ISSUE TITLE
capacity plugin for Swift

### ISSUE THREAD

**Issue by majewsky** [sapcc/limes#18]
- Query Prometheus to fetch the capacity metric submitted by swift-health-statsd. (An appropriate plugin ID would be `swift-health-statsd`.)
- Get Prometheus server URL from config.yaml.
- Maybe the Prometheus client library already has some facility to execute PromQL queries and parse the responses?

**Comment by auhlig** [comment]
Prometheus' golang client is able to query its API ([Ref](https://github.com/prometheus/client_golang#client-for-the-prometheus-http-api)), so I'll give it a try.

**Comment by auhlig** [comment]
It's just the `swift_cluster_storage_capacity_bytes_gauge` metric, right?

**Comment by reimannf** [comment]
yes
