### ISSUE TITLE
Cinder capacity plugin: filter on pools supported by available volume types

### ISSUE THREAD

**Issue by majewsky** [sapcc/limes#29]
The Cinder capacity plugin should only consider capacity in pools that users can actually create volumes in, as determined by the available volume types.

1. As a lightweight initial solution, add a filter to the plugin that matches on `volume_backend_name` in the pool (similar to the existing flavor filtering in the Nova capacity plugin).

2. A more complete solution would be to actually look at the volume types (`openstack volume type list/show`) and use the `properties` noted there, e.g. `volume_backend_name`, `storage_protocol` to match admissible pools.

Number 2 can be put on the back-burner for now since number 1 will cover our immediate needs just fine.

**Comment by auhlig** [comment]
Done 1. via #30

**Comment by majewsky** [comment]
It looks like we don't need number 2.
