### ISSUE TITLE
gophercloud Hypervisors List API 

### ISSUE THREAD

**Issue by auhlig** [sapcc/limes#34]
gophercloud supports compute/v2: Hypervisors List API https://github.com/gophercloud/gophercloud/pull/344. Implement  in nova capacity plugin.

**Comment by majewsky** [comment]
I tried, but it causes weird JSON parsing errors, probably because Gophercloud wants to parse all subdocuments whereas we are only interested in a few basic numeric properties. Let's keep the code that we have, it's working well.
