### ISSUE TITLE
Setting an Initial Domain quota is not possible

### ISSUE THREAD

**Issue by reimannf** [sapcc/limes#36]
Currently I assume there is a mayor bug when setting initial domain quotas:
The following https://github.com/sapcc/limes/blob/f9f1c12bda311313105a9564b21e62b191b7f992/pkg/api/domains.go#L150 will not allow to create new domain quota entries, because it skips the non existing entries in `domain_resouces`.
My first thought was, that the collector should create an initial entry but could not find anything in the code.
In principle I think it is fine to create the entry on demand.

We might not have hit this yet, because we just spawned the first regions with limes only.

@auhlig @majewsky any feedback highly appreciated.

**Comment by majewsky** [comment]
The problem is not just with line 150 (or 163, for that matter). The problem is that the code only loops over the existing entries. I've added a failing testcase on a branch. Let's see if I have enough time until dinner to fix it, too. :)

**Comment by majewsky** [comment]
Ah, I know how this issue was created. `PutDomain` is basically a copy of `PutProject`, but the issue does not exist for projects because the `project_resources` entries are created by the scraper.

**Comment by reimannf** [comment]
@majewsky many thanks. also for the quick PR. We will have a look. At least found it and did not oversee s.th. in the collector
